INSERT INTO public.muppet (id, username, password, real_name) VALUES (1, 'Alberto', null, 'Alberto Viezzi');
INSERT INTO public.muppet (id, username, password, real_name) VALUES (2, 'Roald', null, 'Roald Humar');
INSERT INTO public.muppet (id, username, password, real_name) VALUES (3, 'Giorgio', null, 'Giorgio Scattolini');
INSERT INTO public.muppet (id, username, password, real_name) VALUES (4, 'Stefano', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (5, 'Mario', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (6, 'Daniel', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (7, 'Luca D.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (8, 'Fabio D.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (9, 'Simone M.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (10, 'Nicholas', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (11, 'Max', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (12, 'Davide', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (13, 'Valentino', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (14, 'Jacopo F.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (15, 'Jacopo G.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (16, 'Piero', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (17, 'Giulia', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (18, 'Simone S.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (19, 'Marco M.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (21, 'Martina', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (22, 'Cesare', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (20, 'F. P. G. Feront', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (23, 'Ivo', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (24, 'Stefania M.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (25, 'Ester P.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (26, 'Goranka', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (27, 'Sara A.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (28, 'Barbara B.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (29, 'Luca L.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (30, 'Ospite 1', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (31, 'Ospite 2', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (32, 'Ospite 3', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (33, 'Alessio B.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (34, 'Andrea S.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (35, 'Michele G.', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (36, 'Gheorghe', null, null);
INSERT INTO public.muppet (id, username, password, real_name) VALUES (37, 'Elisabetta', null, null);