INSERT INTO public.ingredient (id, name, price) VALUES (1, 'aglio', null);
INSERT INTO public.ingredient (id, name, price) VALUES (2, 'asparagi', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (3, 'basilico', null);
INSERT INTO public.ingredient (id, name, price) VALUES (4, 'bocconcini di mozzarella', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (5, 'bresaola', null);
INSERT INTO public.ingredient (id, name, price) VALUES (6, 'brie', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (7, 'capperi ', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (8, 'carciofi', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (9, 'cipolla', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (10, 'cornicione ripieno di mozzarella', null);
INSERT INTO public.ingredient (id, name, price) VALUES (11, 'crema tartufata', null);
INSERT INTO public.ingredient (id, name, price) VALUES (12, 'crocchette di patate', null);
INSERT INTO public.ingredient (id, name, price) VALUES (13, 'curry', null);
INSERT INTO public.ingredient (id, name, price) VALUES (14, 'danese', null);
INSERT INTO public.ingredient (id, name, price) VALUES (15, 'friarielli', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (16, 'funghi', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (17, 'funghi chiodini', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (18, 'funghi freschi', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (19, 'funghi porcini', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (20, 'funghi trifolati', null);
INSERT INTO public.ingredient (id, name, price) VALUES (21, 'gamberetti', 2.50);
INSERT INTO public.ingredient (id, name, price) VALUES (22, 'gorgonzola', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (23, 'gorgonzola piccante', null);
INSERT INTO public.ingredient (id, name, price) VALUES (24, 'grana', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (25, 'grana a scaglie', null);
INSERT INTO public.ingredient (id, name, price) VALUES (26, 'latteria', null);
INSERT INTO public.ingredient (id, name, price) VALUES (27, 'mascarpone', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (28, 'melanzane al funghetto', null);
INSERT INTO public.ingredient (id, name, price) VALUES (29, 'melanzane fritte', null);
INSERT INTO public.ingredient (id, name, price) VALUES (30, 'mozzarella', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (31, 'mozzarella bufala', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (32, 'olio', null);
INSERT INTO public.ingredient (id, name, price) VALUES (33, 'olio extravergine di oliva', null);
INSERT INTO public.ingredient (id, name, price) VALUES (34, 'olive', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (35, 'olive verdi', null);
INSERT INTO public.ingredient (id, name, price) VALUES (36, 'origano', null);
INSERT INTO public.ingredient (id, name, price) VALUES (37, 'pancetta', null);
INSERT INTO public.ingredient (id, name, price) VALUES (38, 'pancetta arrosta', null);
INSERT INTO public.ingredient (id, name, price) VALUES (39, 'pancetta stufata', null);
INSERT INTO public.ingredient (id, name, price) VALUES (40, 'panna', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (41, 'patatine fritte', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (42, 'pecorino a scaglie', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (43, 'pepe', null);
INSERT INTO public.ingredient (id, name, price) VALUES (44, 'peperoni', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (45, 'peperoni fritti', null);
INSERT INTO public.ingredient (id, name, price) VALUES (46, 'pomodoro', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (47, 'pomodoro fresco', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (48, 'porchetta', null);
INSERT INTO public.ingredient (id, name, price) VALUES (49, 'prosciutto', null);
INSERT INTO public.ingredient (id, name, price) VALUES (50, 'prosciutto cotto', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (51, 'prosciutto crudo', null);
INSERT INTO public.ingredient (id, name, price) VALUES (52, 'provola affumicata', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (53, 'radicchio di Treviso', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (54, 'ricotta', 1.00);
INSERT INTO public.ingredient (id, name, price) VALUES (55, 'ricotta affumicata a scaglie', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (56, 'rosmarino', null);
INSERT INTO public.ingredient (id, name, price) VALUES (57, 'rucola', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (58, 'salame friulano', null);
INSERT INTO public.ingredient (id, name, price) VALUES (59, 'salame ungherese', null);
INSERT INTO public.ingredient (id, name, price) VALUES (60, 'salamino piccante', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (61, 'salmone affumicato', 2.50);
INSERT INTO public.ingredient (id, name, price) VALUES (62, 'salsiccia', null);
INSERT INTO public.ingredient (id, name, price) VALUES (63, 'salsiccia fresca', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (64, 'sesamo', null);
INSERT INTO public.ingredient (id, name, price) VALUES (65, 'speck', null);
INSERT INTO public.ingredient (id, name, price) VALUES (66, 'stracchino', null);
INSERT INTO public.ingredient (id, name, price) VALUES (67, 'tonno', 2.00);
INSERT INTO public.ingredient (id, name, price) VALUES (68, 'uovo', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (69, 'uovo sodo', null);
INSERT INTO public.ingredient (id, name, price) VALUES (70, 'verdure miste', null);
INSERT INTO public.ingredient (id, name, price) VALUES (71, 'wurstel', 1.50);
INSERT INTO public.ingredient (id, name, price) VALUES (72, 'patate al forno', null);
INSERT INTO public.ingredient (id, name, price) VALUES (73, 'acciughe', null);
INSERT INTO public.ingredient (id, name, price) VALUES (74, 'hamburgher', null);
INSERT INTO public.ingredient (id, name, price) VALUES (75, 'formaggio', null);
INSERT INTO public.ingredient (id, name, price) VALUES (76, 'ketchup', null);
INSERT INTO public.ingredient (id, name, price) VALUES (77, 'salsa rosa', null);
INSERT INTO public.ingredient (id, name, price) VALUES (78, 'maionese', null);
INSERT INTO public.ingredient (id, name, price) VALUES (79, 'insalata', null);
INSERT INTO public.ingredient (id, name, price) VALUES (80, 'Impasto alle Olive', 1.00);