INSERT INTO public.food (id, name, price, type) VALUES (1, 'Marinara', 3.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (2, 'Margherita', 4.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (3, 'Prosciutto', 5.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (5, 'Diavola', 5.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (6, 'Melanzane', 5.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (7, 'Romana', 5.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (8, 'peperoni', 5.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (9, 'Viennese', 5.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (10, 'Rucola', 5.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (11, 'Capricciosa', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (12, '4 Stagioni', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (13, '4 Formaggi', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (14, 'Calzone', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (15, 'Calzone Farcito', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (16, 'Tonno', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (17, 'Caprese', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (18, 'Bufala', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (19, 'Verdure', 6.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (20, 'Fresca', 6.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (21, 'Mascarzone', 6.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (22, 'Calzone Fritto', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (23, 'Golosa', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (24, 'Carbonara', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (25, 'Los Angeles', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (26, 'Super-Crock con Prosciutto', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (27, 'Super-Crock con Porchetta', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (28, 'Super-Crock con Salsiccia', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (29, 'Calzone Saporito', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (30, 'Esplosiva', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (31, 'Meditteranea', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (32, 'Tris di Funghi', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (33, 'Salmone', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (34, 'Tartufata', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (35, 'Boschetto', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (36, 'Saporita', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (37, 'Super-Tartufata', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (38, 'Primavera', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (39, 'Boys', 6.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (40, 'Provolina', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (41, 'Montanara', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (42, 'Trevigiana', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (43, 'Tirolese', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (44, 'Fantastica', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (45, 'Siciliana', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (46, 'Sfiziosa', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (47, 'Bomba', 7.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (48, 'Rustica', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (49, 'Delizia', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (50, 'Delicata', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (51, 'New York', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (52, 'Piccantina', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (53, 'Curry', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (54, 'Bresaola', 7.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (55, 'Fattoria', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (56, 'Simpson', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (57, 'Inverno', 8.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (58, 'Imperiale', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (59, 'Friulana', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (60, 'Estate', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (61, 'Vanessa', 8.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (62, 'Boris', 9.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (63, 'Artisti', 9.50, 1);
INSERT INTO public.food (id, name, price, type) VALUES (64, 'Salumi', 10.00, 1);
INSERT INTO public.food (id, name, price, type) VALUES (65, 'Pollo al Forno e Patate', 8.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (66, 'Pollo Disossato e Patate', 7.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (67, 'Petto di Pollo e Patate', 7.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (68, 'Tagliata di Pollo', 8.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (69, 'Milanese e Patatine Fritte', 7.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (70, 'Scaloppine (al vino, al limone, ai funghi', 7.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (71, 'Ljubljancka', 9.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (72, 'Lonza al Senape e Patate', 8.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (73, 'Salsicce al vino rosso', 6.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (74, 'Grigliata Mista', 13.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (75, 'Calamari Fritti e Patatine', 9.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (76, 'Insalata', 3.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (77, 'Insalata Mista', 4.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (78, 'Insalatona', 7.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (79, 'Patatine Fritte', 3.00, 2);
INSERT INTO public.food (id, name, price, type) VALUES (80, 'Crocchette di Patate', 3.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (81, 'Verdure alla Piastra', 3.50, 2);
INSERT INTO public.food (id, name, price, type) VALUES (82, 'Sfizioso', 6.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (83, 'Classic Burgher', 6.50, 4);
INSERT INTO public.food (id, name, price, type) VALUES (84, 'Hot Dog', 6.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (85, 'Classico', 6.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (86, 'Boss', 7.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (87, 'Super', 7.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (88, 'Estate', 7.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (89, 'Vegetariano', 6.50, 4);
INSERT INTO public.food (id, name, price, type) VALUES (90, 'Rio Mare', 6.00, 4);
INSERT INTO public.food (id, name, price, type) VALUES (91, 'Tiramisu', 3.50, 3);
INSERT INTO public.food (id, name, price, type) VALUES (92, 'Crepes Nutella / Marmellata', 3.50, 3);
INSERT INTO public.food (id, name, price, type) VALUES (93, 'Cornetto alla Nutella', 3.50, 3);
INSERT INTO public.food (id, name, price, type) VALUES (94, 'Tortino al Cioccolato', 2.50, 3);
INSERT INTO public.food (id, name, price, type) VALUES (95, 'Pizza Nutella', 5.00, 3);
INSERT INTO public.food (id, name, price, type) VALUES (96, 'Tartufo Bianco / Nero', 2.50, 3);
INSERT INTO public.food (id, name, price, type) VALUES (4, 'Funghi', 5.00, 1);