version: '3'

services:
    ultimate-pizza-manager:
        image: postgres:${POSTGRES_VERSION}
        environment:
            - POSTGRES_USER=teamYOOX
            - POSTGRES_PASSWORD=we<3YOOX
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres_identity:/var/lib/postgresql
